# -*- coding: utf-8 -*-
"""Spam Email Detection using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbITeveX59CUwHZhZHu0dlrJ3jYfkDEg
"""

# Import required libraries
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# -----------------------------
# Step 1: Create Email Dataset
# -----------------------------
# 1 = Spam, 0 = Not Spam (Ham)

emails = [
    "Win money now",
    "Limited offer just for you",
    "Meeting at 10 am",
    "Project discussion tomorrow",
    "Earn dollars easily",
    "Let's study together"
]

labels = [1, 1, 0, 0, 1, 0]

# -----------------------------
# Step 2: Convert Text to Numbers
# -----------------------------
# Machine learning models understand numbers, not text
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)

# -----------------------------
# Step 3: Train the Model
# -----------------------------
model = MultinomialNB()
model.fit(X, labels)

# -----------------------------
# Step 4: Test the Model
# -----------------------------
test_emails = [
    "Win a free lottery",
    "Let's meet for lunch"
]

test_data = vectorizer.transform(test_emails)

# -----------------------------
# Step 5: Predict Results
# -----------------------------
predictions = model.predict(test_data)

# -----------------------------
# Step 6: Display Output Clearly
# -----------------------------
for i in range(len(test_emails)):
    if predictions[i] == 1:
        print(f"'{test_emails[i]}' --> Spam")
    else:
        print(f"'{test_emails[i]}' --> Not Spam")